title: Josh Simon # your name (or website title) here
logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/josh-simon-634a151b6/">LinkedIn</a> 
  <br>
  <a href="https://bowen.finance/cv/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://www.GitHub.com/jls224/">GitHub</a>  
  <br>

  
theme: jekyll-theme-minimal
